title: Imran Al-Nahdy # your name (or website title) here
logo: "/images/IMG_3417-modified.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm Imran Al-Nahdy, a passionate and results-driven data analyst with a strong finance, business administration, and data science background. My expertise is utilizing programming languages like Python, R, and SQL to build predictive models, uncover actionable insights, and optimize business strategies.
  <br><br>
  With a focus on data-driven decision-making, I've worked on various projects ranging from stock market prediction models to big data pipelines for airlines. My technical proficiency in data visualization tools like Tableau and Power BI allows me to turn complex datasets into clear, impactful presentations for stakeholders.
  <br><be>
  I invite you to explore my projects and see how I can bring a combination of analytical insight, business acumen, and technical expertise to any challenge.
   <br><br>
   Let's turn data into meaningful solutions!
   <br><br>
  <a href="https://www.linkedin.com/in/imran-al-nahdy-20b473182">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
