title: Imran Al-Nahdy # your name (or website title) here
logo: "/images/IMG_3417-modified.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  1 year of banking experience with extensive knowledge in Microsoft suite, Python and R.
  Currently enrolled in a Masters of Business Analytics and Artificial Intelligence program at 
  OntarioTech University.
  <br><br>
  Bachelor of Commerce graduate majoring in Finance. Extensive retail experience. 
  <br><br>
  <a href="https://www.linkedin.com/in/imran-al-nahdy-20b473182">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
